### PR TITLE
php8 compatibility

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by basz** [comment]
yay https://app.travis-ci.com/github/basz/pdo-snapshot-store/builds/255038526

dropped some eol databases. still tested mysql 5.7 + 8.0, postgresql 10, mariadb 10.3

**Comment by basz** [comment]
please review @prolic

**Comment by prolic** [comment]
@basz Travis says: "Builds have been temporarily disabled for public repositories due to a negative credit balance."

Wanna go ahead and replace with github actions?

**Comment by basz** [comment]
Aware.
Now you've accepted the other or with a conversion to GitHub actions I'll do these too...

**Comment by prolic** [comment]
awesome, waiting for PR's then

**Pull request merged**
